name: deploy to anjos.github.io/cv

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: index.docker.io/aergus/latex
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        shell: bash -l {0}
        run: |
            make cv.pdf
            mkdir output
            cp cv.pdf output/
            cp publications.bib output/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./output
            publish_branch: gh-pages
